// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1Mwhwq7W-pBdW0eOHfkIJu4uqUyx_M6I',
    appId: '1:853624061612:web:20416e9ead83f4e479e909',
    messagingSenderId: '853624061612',
    projectId: 'chat-app-44332',
    authDomain: 'chat-app-44332.firebaseapp.com',
    storageBucket: 'chat-app-44332.firebasestorage.app',
    measurementId: 'G-SJYL9XQHNV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlIwcpoAVP0B3U1UaDEp_6Ne5NoMVjbXk',
    appId: '1:853624061612:android:abe4cf28a694c99d79e909',
    messagingSenderId: '853624061612',
    projectId: 'chat-app-44332',
    storageBucket: 'chat-app-44332.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHuyVgIn7qXzGYZfEjWazBXjpLC3TRdAc',
    appId: '1:853624061612:ios:5f9a410f6a07345979e909',
    messagingSenderId: '853624061612',
    projectId: 'chat-app-44332',
    storageBucket: 'chat-app-44332.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHuyVgIn7qXzGYZfEjWazBXjpLC3TRdAc',
    appId: '1:853624061612:ios:5f9a410f6a07345979e909',
    messagingSenderId: '853624061612',
    projectId: 'chat-app-44332',
    storageBucket: 'chat-app-44332.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1Mwhwq7W-pBdW0eOHfkIJu4uqUyx_M6I',
    appId: '1:853624061612:web:bc534157e5c7a12679e909',
    messagingSenderId: '853624061612',
    projectId: 'chat-app-44332',
    authDomain: 'chat-app-44332.firebaseapp.com',
    storageBucket: 'chat-app-44332.firebasestorage.app',
    measurementId: 'G-NLHSFMLBCJ',
  );
}
